export type SponsorProfile =
  | "PE"
  | "REIT"
  | "Developer"
  | "Family Office"
  | "Corporate";

export type TransactionType =
  | "Investment Sale"
  | "Debt Placement"
  | "Equity Placement"
  | "Recapitalization";

export type Region =
  | "Texas"
  | "Southeast"
  | "Midwest"
  | "West"
  | "Northeast";

export type Segment =
  | "Select Service"
  | "Full Service"
  | "Resort"
  | "Lifestyle"
  | "Boutique"
  | "Extended Stay";

export type ClosedDeal = {
  slug: string;
  name: string;
  city: string;
  state: string;
  region: Region;
  year: number;
  segment: Segment;
  brand?: string;
  keys: number;
  dealSize: string;
  transactionType: TransactionType;
  // Source-faithful label (e.g. "Asset Sale + Bridge Financing"). When present,
  // the card displays this instead of the normalized enum. Filters still use
  // `transactionType` so the dropdown stays at the four canonical buckets.
  transactionTypeLabel?: string;
  // Per-deal hero photo, served from /public/closed/. When omitted, the card
  // renders text-only.
  photo?: string;
  sponsorProfile: SponsorProfile;
  brokerSlugs: string[];
  toneClass: string;
};

export const closed: ClosedDeal[] = [
  // === MCC Capital Markets, Debt Placement Track Record ===
  // Sourced from "MCC Deals for Matthews" (May 2026).
  // Some keys are estimates (source sheet listed total raise / fees only).
  {
    slug: "26-hotel-portfolio-acquisition-debt",
    name: "26-Hotel Acquisition Portfolio",
    city: "Multi-Asset",
    state: "FL",
    region: "Southeast",
    year: 2021,
    segment: "Select Service",
    brand: "Multi-Brand",
    keys: 2600,
    dealSize: "$90,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Debt Fund + Mezz Placement",
    sponsorProfile: "PE",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "courtyard-lake-charles-debt",
    name: "Courtyard by Marriott Lake Charles",
    city: "Lake Charles",
    state: "LA",
    region: "Southeast",
    year: 2020,
    segment: "Select Service",
    brand: "Marriott",
    keys: 142,
    dealSize: "$10,850,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "CMBS Debt Placement",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "marriott-2-pack-del-mar-debt",
    name: "Marriott 2-Pack Del Mar (Select + Full Service)",
    city: "Del Mar",
    state: "CA",
    region: "West",
    year: 2019,
    segment: "Full Service",
    brand: "Marriott",
    keys: 500,
    dealSize: "$100,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Bank Debt Placement",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "full-service-marriott-fort-collins-debt",
    name: "Full Service Marriott Fort Collins",
    city: "Fort Collins",
    state: "CO",
    region: "West",
    year: 2019,
    segment: "Full Service",
    brand: "Marriott",
    keys: 250,
    dealSize: "$26,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "CMBS Debt Placement",
    sponsorProfile: "PE",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "4-pack-marriott-intercon-portfolio-debt",
    name: "4-Pack Portfolio (3 Marriott + InterContinental)",
    city: "Multi-City",
    state: "FL",
    region: "Southeast",
    year: 2019,
    segment: "Full Service",
    brand: "Multi-Brand",
    keys: 1000,
    dealSize: "$200,000,000",
    transactionType: "Debt Placement",
    sponsorProfile: "PE",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },

  // === Capital Markets Track Record (extended) ===
  // Sourced from the team's printed transaction sheet (May 2026).
  // TODO: confirm year, key counts, and sponsorProfile per deal with broker
  // before the next data refresh, the source sheet listed only Tenant /
  // City / State / Amount / Type. Brand inferred from flag, segment from
  // brand archetype, region from state.
  {
    slug: "residence-inn-san-marcos-construction",
    name: "Residence Inn San Marcos",
    city: "San Marcos",
    state: "TX",
    region: "Texas",
    year: 2021,
    segment: "Extended Stay",
    brand: "Marriott",
    keys: 110,
    dealSize: "$12,350,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Construction Financing",
    photo: "/closed/residence-inn-san-marcos.jpg",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "staybridge-suites-austin-permanent",
    name: "Staybridge Suites Austin",
    city: "Austin",
    state: "TX",
    region: "Texas",
    year: 2021,
    segment: "Extended Stay",
    brand: "IHG",
    keys: 121,
    dealSize: "$11,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    photo: "/closed/staybridge-suites-austin.jpg",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "country-inn-suites-augusta-cmbs",
    name: "Country Inn & Suites Augusta",
    city: "Augusta",
    state: "GA",
    region: "Southeast",
    year: 2020,
    segment: "Select Service",
    brand: "Radisson",
    keys: 80,
    dealSize: "$4,700,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale + CMBS Assumption",
    photo: "/closed/country-inn-suites-augusta.jpg",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "hampton-inn-portfolio-atlanta-sale-bridge",
    name: "Hampton Inn Portfolio Atlanta",
    city: "Atlanta",
    state: "GA",
    region: "Southeast",
    year: 2021,
    segment: "Select Service",
    brand: "Hilton",
    keys: 540,
    dealSize: "$49,900,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale + Bridge Financing",
    sponsorProfile: "PE",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    photo: "/closed/hampton-inn-portfolio-atlanta.jpg",
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "crown-plaza-downtown-dallas-permanent",
    name: "Crown Plaza Downtown Dallas",
    city: "Dallas",
    state: "TX",
    region: "Texas",
    year: 2020,
    segment: "Full Service",
    brand: "IHG",
    keys: 311,
    dealSize: "$27,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    photo: "/closed/crown-plaza-downtown-dallas.jpg",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },
  {
    slug: "radisson-hotel-corning-sale",
    name: "Radisson Hotel Corning",
    city: "Corning",
    state: "NY",
    region: "Northeast",
    year: 2019,
    segment: "Full Service",
    brand: "Radisson",
    keys: 180,
    dealSize: "$16,500,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "hilton-garden-inn-bozeman-permanent",
    name: "Hilton Garden Inn Bozeman",
    city: "Bozeman",
    state: "MT",
    region: "West",
    year: 2021,
    segment: "Select Service",
    brand: "Hilton",
    keys: 124,
    dealSize: "$11,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "hampton-inn-suites-beaumont-sale-bridge",
    name: "Hampton Inn & Suites Beaumont",
    city: "Beaumont",
    state: "TX",
    region: "Texas",
    year: 2020,
    segment: "Select Service",
    brand: "Hilton",
    keys: 122,
    dealSize: "$11,700,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale + Bridge Financing",
    photo: "/closed/hampton-inn-suites-beaumont.jpg",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "stone-mountain-lodge-lyons-sale-bridge",
    name: "Stone Mountain Lodge",
    city: "Lyons",
    state: "CO",
    region: "West",
    year: 2020,
    segment: "Resort",
    brand: "Independent",
    keys: 40,
    dealSize: "$3,700,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale + Bridge Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "holiday-inn-express-augusta-sale-bridge",
    name: "Holiday Inn Express Augusta",
    city: "Augusta",
    state: "GA",
    region: "Southeast",
    year: 2021,
    segment: "Select Service",
    brand: "IHG",
    keys: 119,
    dealSize: "$18,300,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale + Bridge Financing",
    sponsorProfile: "PE",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },
  {
    slug: "ramada-houston-permanent",
    name: "Ramada Houston",
    city: "Houston",
    state: "TX",
    region: "Texas",
    year: 2019,
    segment: "Select Service",
    brand: "Wyndham",
    keys: 100,
    dealSize: "$4,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "staybridge-suites-houston-permanent",
    name: "Staybridge Suites Houston",
    city: "Houston",
    state: "TX",
    region: "Texas",
    year: 2020,
    segment: "Extended Stay",
    brand: "IHG",
    keys: 121,
    dealSize: "$7,200,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    photo: "/closed/staybridge-suites-houston.jpg",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "country-inn-suites-san-antonio-permanent",
    name: "Country Inn & Suites San Antonio",
    city: "San Antonio",
    state: "TX",
    region: "Texas",
    year: 2020,
    segment: "Select Service",
    brand: "Radisson",
    keys: 70,
    dealSize: "$3,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    photo: "/closed/country-inn-suites-san-antonio.jpg",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "resort-at-paws-up-missoula-permanent",
    name: "The Resort at Paws Up",
    city: "Missoula",
    state: "MT",
    region: "West",
    year: 2021,
    segment: "Resort",
    brand: "Independent",
    keys: 52,
    dealSize: "$15,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    photo: "/closed/resort-at-paws-up.jpg",
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "mansion-at-judges-hill-austin-sale",
    name: "The Mansion at Judges Hill",
    city: "Austin",
    state: "TX",
    region: "Texas",
    year: 2021,
    segment: "Boutique",
    brand: "Independent",
    keys: 14,
    dealSize: "$10,000,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Asset Sale",
    photo: "/closed/mansion-at-judges-hill.jpg",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },

  // === Capital Markets Track Record (page 1, Preferred Equity + Construction
  //     + Permanent Financing) — added May 2026 from source sheet. ===
  // Brand/segment/region inferred; year and keys are estimates pending broker
  // confirmation. Filter buckets use the canonical transactionType enum;
  // transactionTypeLabel preserves the source-faithful label.
  {
    slug: "hampton-home2-suites-austin-pref-equity",
    name: "Hampton + Home2 Suites Austin",
    city: "Austin",
    state: "TX",
    region: "Texas",
    year: 2021,
    segment: "Select Service",
    brand: "Hilton",
    keys: 240,
    dealSize: "$36,500,000",
    transactionType: "Equity Placement",
    transactionTypeLabel: "Preferred Equity",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "tampa-boutique-multifamily-pref-equity",
    name: "Tampa Boutique Multifamily",
    city: "Tampa",
    state: "FL",
    region: "Southeast",
    year: 2021,
    segment: "Boutique",
    brand: "Independent",
    keys: 120,
    dealSize: "$10,000,000",
    transactionType: "Equity Placement",
    transactionTypeLabel: "Preferred Equity",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "home2-suites-del-rio-construction",
    name: "Home2 Suites by Hilton Del Rio",
    city: "Del Rio",
    state: "TX",
    region: "Texas",
    year: 2020,
    segment: "Extended Stay",
    brand: "Hilton",
    keys: 89,
    dealSize: "$17,550,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Development + Construction Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "dual-brand-hampton-home2-austin-construction",
    name: "Dual Brand Hampton Inn + Home2 Suites Austin",
    city: "Austin",
    state: "TX",
    region: "Texas",
    year: 2021,
    segment: "Select Service",
    brand: "Hilton",
    keys: 260,
    dealSize: "$65,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Development + Construction Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "hampton-inn-beaumont-permanent",
    name: "Hampton Inn Beaumont",
    city: "Beaumont",
    state: "TX",
    region: "Texas",
    year: 2019,
    segment: "Select Service",
    brand: "Hilton",
    keys: 120,
    dealSize: "$5,750,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },
  {
    slug: "home2-suites-columbus-permanent",
    name: "Home2 Suites Columbus",
    city: "Columbus",
    state: "OH",
    region: "Midwest",
    year: 2020,
    segment: "Extended Stay",
    brand: "Hilton",
    keys: 110,
    dealSize: "$11,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "hampton-inn-suites-altoona-permanent",
    name: "Hampton Inn & Suites Altoona",
    city: "Altoona",
    state: "IA",
    region: "Midwest",
    year: 2020,
    segment: "Select Service",
    brand: "Hilton",
    keys: 96,
    dealSize: "$9,200,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "la-quinta-inn-suites-waco-permanent",
    name: "La Quinta Inn & Suites Waco",
    city: "Waco",
    state: "TX",
    region: "Texas",
    year: 2019,
    segment: "Select Service",
    brand: "Wyndham",
    keys: 100,
    dealSize: "$9,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "holiday-inn-express-early-permanent",
    name: "Holiday Inn Express Early",
    city: "Early",
    state: "TX",
    region: "Texas",
    year: 2020,
    segment: "Select Service",
    brand: "IHG",
    keys: 80,
    dealSize: "$8,400,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "firebrand-hotel-whitefish-permanent",
    name: "Firebrand Hotel",
    city: "Whitefish",
    state: "MT",
    region: "West",
    year: 2021,
    segment: "Boutique",
    brand: "Independent",
    keys: 86,
    dealSize: "$14,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },
  {
    slug: "home2-suites-hanford-permanent",
    name: "Home2 Suites Hanford",
    city: "Hanford",
    state: "CA",
    region: "West",
    year: 2020,
    segment: "Extended Stay",
    brand: "Hilton",
    keys: 105,
    dealSize: "$13,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "hampton-inn-home2-suites-tulsa-permanent",
    name: "Hampton Inn & Home2 Suites Tulsa",
    city: "Tulsa",
    state: "OK",
    region: "Midwest",
    year: 2021,
    segment: "Select Service",
    brand: "Hilton",
    keys: 210,
    dealSize: "$21,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
  {
    slug: "marble-falls-hotel-land-purchase",
    name: "Marble Falls Hotel",
    city: "Marble Falls",
    state: "TX",
    region: "Texas",
    year: 2019,
    segment: "Select Service",
    brand: "Independent",
    keys: 0,
    dealSize: "$635,000",
    transactionType: "Investment Sale",
    transactionTypeLabel: "Land Purchase",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0a1226] to-[#1a3a6b]",
  },
  {
    slug: "quality-inn-carthage-permanent",
    name: "Quality Inn Carthage",
    city: "Carthage",
    state: "TX",
    region: "Texas",
    year: 2019,
    segment: "Select Service",
    brand: "Choice",
    keys: 60,
    dealSize: "$1,600,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1d1d1f] to-[#2c2c2e]",
  },
  {
    slug: "home2-suites-merrillville-permanent",
    name: "Home2 Suites Merrillville",
    city: "Merrillville",
    state: "IN",
    region: "Midwest",
    year: 2020,
    segment: "Extended Stay",
    brand: "Hilton",
    keys: 100,
    dealSize: "$10,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0066cc] to-[#1a56db]",
  },
  {
    slug: "home2-suites-austin-permanent",
    name: "Home2 Suites Austin",
    city: "Austin",
    state: "TX",
    region: "Texas",
    year: 2021,
    segment: "Extended Stay",
    brand: "Hilton",
    keys: 132,
    dealSize: "$21,500,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Developer",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#1a3a6b] to-[#0066cc]",
  },
  {
    slug: "holiday-inn-vidor-permanent",
    name: "Holiday Inn Vidor",
    city: "Vidor",
    state: "TX",
    region: "Texas",
    year: 2019,
    segment: "Full Service",
    brand: "IHG",
    keys: 100,
    dealSize: "$4,000,000",
    transactionType: "Debt Placement",
    transactionTypeLabel: "Permanent Financing",
    sponsorProfile: "Family Office",
    brokerSlugs: ["luke-thompson", "miles-cortez"],
    toneClass: "from-[#0e1a34] to-[#1a3a6b]",
  },
];

/* --------------------------------------------------------------------------
 * Photo mapping, closed-deal cards use stock-archetype photos by segment.
 * Photos live in /public/closed/ (sourced from Unsplash). Each segment
 * cycles through its available photos in deal-list order so adjacent cards
 * in the grid don't repeat.
 * ------------------------------------------------------------------------ */

const SEGMENT_PHOTOS: Record<Segment, string[]> = {
  "Select Service": [
    "/closed/select-service-1.jpg",
    "/closed/select-service-2.jpg",
    "/closed/select-service-3.jpg",
  ],
  "Full Service": [
    "/closed/full-service-1.jpg",
    "/closed/full-service-2.jpg",
  ],
  Resort: ["/closed/resort-1.jpg", "/closed/resort-2.jpg"],
  Lifestyle: ["/closed/lifestyle-1.jpg"],
  Boutique: ["/closed/boutique-historic-1.jpg"],
  "Extended Stay": ["/closed/extended-stay-1.jpg"],
};

/**
 * Returns a stable photo for a closed deal: cycles through the available
 * archetype photos for that segment based on the deal's index in the
 * filtered segment list. Same deal → same photo, every render.
 */
export function getDealPhoto(deal: ClosedDeal): string {
  const photos = SEGMENT_PHOTOS[deal.segment];
  if (!photos || photos.length === 0) return "/closed/select-service-1.jpg";
  // Index within same-segment deals, in canonical `closed` array order.
  const sameSegment = closed.filter((d) => d.segment === deal.segment);
  const idx = sameSegment.findIndex((d) => d.slug === deal.slug);
  return photos[idx % photos.length];
}

/**
 * Parse a deal-size string like "$19,400,000" into a number.
 * Returns NaN for "Confidential" so it can be sorted last.
 */
export function parseDealSize(value: string): number {
  if (!value || /confidential/i.test(value)) return NaN;
  const cleaned = value.replace(/[^0-9.]/g, "");
  const num = parseFloat(cleaned);
  return Number.isFinite(num) ? num : NaN;
}

/** Sum all numeric deal sizes (skipping Confidential). */
export function totalKnownVolume(items: ClosedDeal[] = closed): number {
  return items.reduce((sum, d) => {
    const n = parseDealSize(d.dealSize);
    return Number.isFinite(n) ? sum + n : sum;
  }, 0);
}
